#server config
server:
  port: 8080

#logging config
logging:
  level:
    org:
      springframework:
        web: DEBUG
        data:
          mongodb: DEBUG

spring:

  #mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: dev
    password: dev
    url: jdbc:mysql://localhost:3306/mini_market_db

  #jpa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

    flyway:
      enabled: true
      password: dev
      user: dev

  #mongo
  data:
    mongodb:
      database: mini_market_db
      host: localhost
      port: 27017
      username: dev
      password: dev
      authentication-database: admin

#jwt
jwt:
  secret: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
  type: JWT